version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: onesight
      POSTGRES_HOST: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - onesight-api-postgres:/var/lib/postgresql/data

volumes:
  onesight-api-postgres: